server:
  port: 8081
  servlet:
    context-path: /shop
    multipart:
      max-file-size: 10MB  #单个文件
      max-request-size: 100MB #总文件大小

spring:
     datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/db_shopmaster?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
     jpa:
       show-sql: true
     mvc:
       view:
         prefix: /WEB-INF/views/
         suffix: .jsp


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhang.ssmschoolshop.entity
   #devtools插件
devtools:
    restart:
      enabled: true #是否支持热部署
#mybaatis分页插件pagehelper设置
pagehelper:
  pagehelperDialect: mysql
  reasonable: true
  support-methods-arguments: true

  # 打印sql
logging:
    level:
       com.zhang.ssmschoolshop.dao: DEBUG


mail:
  host: smtp.qq.com
  username: #your email
  password: #email 授权码
  default-encoding: UTF-8
  protocol: smtp
  properties:
    mail:
      smtp:
        ssl:
          enable: true
  #spring.mail.port: 25
  from: 1452212105@qq.com
  receive:  #收件者邮箱
  test-connection: false





# 接口访问  http://127.0.0.1:8081/shop/swagger-ui.html
# 管理员访问 http://127.0.0.1:8081/shop/admin/login

# admin 12345678

# root  12345678
# codingzx  12345678
# admin 12345678
 # session 和 cookie的区别
 # 增加超卖逻辑
#  定时任务 每天查看异常订单
#  引入死信队列进行处理
#  图片保存在D；/upload文件夹
#  线程池
#  压测工具sb
